
import { Header } from '@/shared/components/shared';
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function Layout ({ children } : Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='min-h-screen'>
        <Header/>
        {children}
    </main>
  );
};